---
version: '3'
services :
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: tododb
    volumes:
      - postgres-data:/var/lib/postgresql/data
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
  rstudio:
    image: rocker/rstudio
    ports:
      - "8787:8787"
      # - "3838:3838"
    environment:
      # ADD: shiny
      USERID: ${UID}
      UMASK: 022
    volumes:
      - ./rstudio/:/home/rstudio
volumes:
  postgres-data:
